version: "3.9"

services:
  backend:
    build:
      context: ./Backend
    container_name: shopper_backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: mysql://root:root@db:3306/shopper_teste
      PORT: 8080
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    depends_on:
      - db
    networks:
      - shopper_network

  frontend:
    build:
      context: ./Frontend
    container_name: shopper_frontend
    ports:
      - "80:80"
    networks:
      - shopper_network

  db:
    image: mysql:8.0
    container_name: shopper_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopper_teste
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shopper_network

volumes:
  db_data:

networks:
  shopper_network:
    driver: bridge
