version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: shopper_teste_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - shopper_network

  backend:
    build: .
    container_name: shopper_backend
    ports:
      - ${PORT}:${PORT}
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    depends_on:
      - db
    networks:
      - shopper_network

volumes:
  db_data:

networks:
  shopper_network:
    driver: bridge
